services:
  backend:
    container_name: backend
    build:
      context: ./backend
      args:
        - PB_VERSION=0.23.1
    volumes:
      - pb_data:/home/default/pb_data
    ports:
      - 4322:4322
    init: true

volumes:
  pb_data: